baseurl = "https://abstractlambda.com/"
publishdir = "../"
title = "abstract lambdas"
author = "zach maas"
canonifyurls = true
languagecode = "en"
theme = "ultramin"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "things by zach"
  subname = "zach maas"

[[menu.main]]
    name = "about"
    url  = "/about/"
[[menu.main]]
    name = "blog"
    url  = "/blog/"
[[menu.main]]
    name = "projects"
    url  = "/projects/"
[[menu.main]]
    name = "resume"
    url  = "https://github.com/zmaas/"
