#+HUGO_BASE_DIR: ./
* index
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_FILE_NAME: _index
:EXPORT_DATE: 2018-05-13
:END:
I'm zach, this is my website. Right now I'm in school studying Chemistry and Math at CU Boulder and working on Biochemistry research on quantifyng pausing in next-generation sequencing data. Looking for something to read? You might like to see:

- My reading list
- Some things I've worked on
- Some articles I enjoyed
* about
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: about
  :END:
** About Me
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_DATE: 2018-05-13
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:
*** Academic
I'm a student of chemistry and mathematics at the University of Colorado: Boulder. I work as an Undergraduate researcher in computational biochemistry in the [Taatjes](http://www.colorado.edu/chemistry/taatjeslab/) and [Dowell](http://dowell.colorado.edu/) labs at CU. In the lab, I'm working on the techniques we use to quantify sequencing data.
*** Personal
I host my PGP key and keybase verification on this site. My PGP key fingerprint is:

*F500 ABA7 892C E703 608B  6926 2E23 C589 64CC 0B0D*

You can find my full key and keybase verification here:
- [[../keybase.txt][Keybase Verification]]
- [[../pgp_key.asc][PGP key]]
* blog
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: blog
  :END:
** What this site runs on
:PROPERTIES:
:EXPORT_FILE_NAME: site-setup.md
:EXPORT_DATE: 2018-05-13
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :description "Setting up Github Pages with Google Domains and Mailgun" :type "post"
:END:
This site took a little while to get up and running, with a few tricks needed here and there, but now that it's all setup, the editing workflow is surprisingly smooth.

First things first, this site is hosted using [[https://gohugo.io][Hugo]], a quick and easy static site generator. I played around with alternatives like [[https://jekyllrb.com][Jekyll]], [[https://hexo.io][Hexo]], and even the haskell-based [[https://jaspervdj.be/hakyll/][Hakyll]], before settling on Hugo almost entirely because of the incredibly fast build times. This site is based on the [[https://github.com/zmaas/hugo-ultramin][ultramin ]]theme for Hugo, which is a minimal theme that I designed.

For domain registration, I use Google Domains which is similarly easy to use, and cheap as well. The site itself is hosted on github pages at the address [[https://zmaas.github.io][zmaas.github.io]]. Then, cloudflare is used to forward the domain to the [[https://abstractlambda.com][abstractlambda.com]] address, in addition to providing support for things like HSTS and site caching. Even though static sites like this are fast, they can be even faster using Cloudflare.

Finally, email addresses for this domain are setup using [[https://www.mailgun.com][mailgun.com]], which works fine for my use cases even with the 10,000 email per month free limit. With all that considered, the only cost for this site is domain registration, which Google Domains prices at $12 a year for .com domains.

For actually writing articles I use a heavily customized Emacs, configured with prodigy.el to run Hugo's serve command whenever I am actively editing an article. In addition, I keep all posts in a single org-mode file and use ox-hugo to export posts when they're ready to be published. When I want to update the actual site, I just commit the changes and push them to github. Nice and easy.
** TODO Making ASCII art with common lisp
:PROPERTIES:
:EXPORT_FILE_NAME: ascii-cl.md
:EXPORT_DATE: 2018-05-13
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :description "Setting up Github Pages with Google Domains and Mailgun" :type "post"
:END:
* license
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: license
  :END:
** License
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_DATE: 2018-05-13
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:
:END:

The content of this site itself licensed under the [[https://creativecommons.org/licenses/by/3.0/us/legalcode][Creative Commons Attribution 3.0 license]], and the underlying source code is licensed under the [[/LICENSE_MIT][MIT License]].

* projects
:PROPERTIES:
:EXPORT_HUGO_SECTION: projects
:EXPORT_FILE_NAME: _index
:EXPORT_DATE: 2017-06-23
:END:
** Personal Projects
- .emacs.d -- I keep my emacs configuration published on github. If you're interested, you can check it out *[[https://github.com/zmaas/.emacs.d][here]]*.

- evil-unimpaired -- This is a small port of Tim Pope's unimpaired.vim, which provides overloading of the square bracket keys to many useful functions. My source, originally pulled from Spacemacs, can be found at [[https://github.com/zmaas/evil-unimpaired][zmaas/evil-unimpaired]]
